server:
  port: 8765

spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: test
            uri: lb://eclient
            predicates:
              - Path=/test
              - Method=GET
  application:
    name: api-gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
